### ISSUE TITLE
permittedValues.includes is not a function

### ISSUE THREAD

**Issue by ruswerner** [joshuapinter/apphubdeploy#6]
I get this error when trying to deploy a build:

```
/Users/rus/.nvm/versions/node/v4.4.4/lib/node_modules/apphubdeploy/AppHubDeploy.js:65
  if (program.target && !permittedValues.includes(program.target)) {
                                         ^

TypeError: permittedValues.includes is not a function
    at checkOptionValues (/Users/rus/.nvm/versions/node/v4.4.4/lib/node_modules/apphubdeploy/AppHubDeploy.js:65:42)
    at Object.<anonymous> (/Users/rus/.nvm/versions/node/v4.4.4/lib/node_modules/apphubdeploy/AppHubDeploy.js:34:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by joshuapinter** [comment]
Somebody else ran into this as well.

Can you try updating your node version and let me know if that fixes it?

Here's mine: 

``` bash
$ node -v
v5.5.0
```

**Comment by ruswerner** [comment]
I had to add this flag to the binary script `--harmony_array_includes`

`":" //# comment; exec /usr/bin/env node --harmony --harmony_array_includes "$0" "$@"`

**Comment by ruswerner** [comment]
I can't update my node version b/c this is the version we use on our production app.

**Comment by joshuapinter** [comment]
Brilliant. I'll add that. Can you give me your node version so I can run some tests as well? 

Thanks. 

Josh

**Comment by ruswerner** [comment]
I'm on node 4.4.4

**Comment by ruswerner** [comment]
However any node version 4.x should have the same behaviour. I think they just released Node 4.6.0 today/yesterday.

**Comment by joshuapinter** [comment]
👍  Perfect, thanks.
